version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.64.0
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
